version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"  # Localstack main endpoint
      - "4572:4572"  # S3 endpoint (deprecated but still accessible)
    environment:
      - SERVICES=s3
      - DEBUG=1
    volumes:
      - "./localstack-data:/var/lib/localstack"
